/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    IEpLink: typeof import('~icons/ep/link')['default']
    MyCampus: typeof import('./components/info/MyCampus.vue')['default']
    MyChannel: typeof import('./components/info/MyChannel.vue')['default']
    MyCompetitions: typeof import('./components/info/MyCompetitions.vue')['default']
    MyContact: typeof import('./components/info/MyContact.vue')['default']
    MyEdu: typeof import('./components/info/MyEdu.vue')['default']
    MyPersonalTag: typeof import('./components/info/MyPersonalTag.vue')['default']
    MyProjects: typeof import('./components/info/MyProjects.vue')['default']
    MyProjectScrollbar: typeof import('./components/info/MyProjectScrollbar.vue')['default']
    MyRadarEchart: typeof import('./components/info/MyRadarEchart.vue')['default']
    MySkills: typeof import('./components/info/MySkills.vue')['default']
    MyWork: typeof import('./components/info/MyWork.vue')['default']
    MyWorkRecord01: typeof import('./components/info/MyWorkRecord01.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/common/SvgIcon.vue')['default']
  }
}
